### ISSUE TITLE
[Deploy Contract] Integrate whitelist api functionality into dApp

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/dApp#129]
### User Story

For reference see #87 and the new  repo here - https://github.com/MARKETProtocol/backend

### Why Is this Needed?

*Summary*: Integrate our new back end functionality into the dApp

### Description
*Type*: Feature

Create needed calls in contract deployment to the backend api to request addition to the whitelist / registry
Create messaging to user that their contract has been sent to MARKET Protocol for review before being added to the Registry

### Additional Information

@StevenJNPearce will take care of this as part of the previous larger issue in #87

**Comment by rojosnow** [comment]
I'm jumping in on this. Working now to scope the LOE.

**Comment by rojosnow** [comment]
Dev API is deployed at, https://fwtl7l0k4i.execute-api.us-west-2.amazonaws.com/dev. All supported endpoints, per the Google Sheet above, return mock data. All data structures are placeholders.

**Comment by pelsasser** [comment]
@rojosnow - wow! thanks!

Let's go over this on the call today and how it integrates with the existing serverless work that has already been done [here](https://github.com/MARKETProtocol/backend)

Can you shed some light on the reason for the us-west-2 location?

Pretty excited to have this in place, definitely a step in the right direction for some of the dApp components and simplifying our contract creation process.

**Comment by rojosnow** [comment]
@pelsasser I spent some time yesterday with the work @StevenJNPearce did with the whitelist functionality. It's a great start. The piece that was missing (not that it was asked of him) was the higher level thinking behind the API. All of the mock API calls can be backended with a variety of services including Lambda. That's where his work will snap in so we're good there.

Also, I'm a big fan of starting simple and adding complexity when necessary to solve problems as they arise...avoiding premature optimization. In practical terms, there is an entire ecosystem already build on AWS for most things we need especially in the CI/CD area. It's best to exhaust the AWS tools then move on when needed to other larger, most sophisticated ones.

The example I'll use is with CloudFormation. At Gaia, we started with CloudFormation and after a bit moved on to Terraform (open source) then to Terraform Enterprise. Each step was very painful and our small DevOps team really felt the heat since our deployment processes came to a screeching halt each time. Let's just say the leader of Ops had a lot of interesting conversations with exec management... ;) The learning here was that we didn't need Terraform but got caught in rabbit holes and "shiny and new" syndrome.

Which region would you like to deploy in? This was a POC and easily movable.

**Comment by rojosnow** [comment]
Deployed endpoints:

- https://rbfo0jcfwj.execute-api.us-east-1.amazonaws.com/dev (dev only, breaking changes will exist).
- https://rbfo0jcfwj.execute-api.us-east-1.amazonaws.com/test (test only, appropriate for test/stage/beta of dapp). **Setup a variable to the URL in the dapp since this will change to something more friendly like, `test.api.marketprotocol.io`**.
- https://rbfo0jcfwj.execute-api.us-east-1.amazonaws.com/test/contracts/whitelist (returns a list of addresses from `getAddressWhiteList`).

API details here: https://docs.google.com/spreadsheets/d/11P2ZZ4eYxDoAD2sSqT1-Nda5Ej5H1Wap_kFb8sK10e4/edit#gid=0

TODOs:

1. Setup Lambda execution environment to troubleshoot add to whitelist code.
2. Fix and deploy add to whitelist.
3. Refactor from `web3@1.0.0-beta.33` to `web3@0.20.6`.
4. Add automated deployment.

**Comment by rojosnow** [comment]
TODOs:

1. (DONE) Setup Lambda execution environment to troubleshoot add to whitelist code.
2. (INPROGRESS) Fix and deploy add to whitelist.
3. Refactor from web3@1.0.0-beta.33 to web3@0.20.6.
4. Add automated deployment.
5. HOWTO on setting up a local dev environment to work on serverless code.

There is still a bit more work to be done to have a local dev environment that others can easily use. Adding that to the todo list.

I've scoped the work needed to fix the issue for bullet 2. The promise chains need some work to return the correct information (HTTP codes, MESSAGING) from the Lambda functions. I'll be working on this today and hopefully will complete it.

Once I'm completed with bullet 2, this will unblock you guys and the rest of the work will not be on the critical path.

@eswarasai @pelsasser

**Comment by rojosnow** [comment]
TODOs:

1. (DONE) Setup Lambda execution environment to troubleshoot add to whitelist code.
2. (DONE) Fix and deploy add to whitelist.
3. (INPROGRESS) Add a "remove from white list" function for testing.
4. Refactor from web3@1.0.0-beta.33 to web3@0.20.6.
5. Add automated deployment/testing.
6. HOWTO on setting up a local dev environment to work on serverless code.

The endpoints "work" on test. 
https://rbfo0jcfwj.execute-api.us-east-1.amazonaws.com/test/contracts/whitelist (GET & POST)

If you try to add to the white list, with an address that has already been added, you get `Returned error: insufficient funds for gas * price + value`. I haven't had time to dig into the code to find out why. It would be good if you could smoke test "add to white list" in the dapp. If it fails, it should give you a descriptive error and a 502 response.

I'll commit some code tomorrow. That was the easy part. The issue was dealing with API Gateway/Lambda docs that have inaccurate/conflicting information regarding passing response/error objects. Adding the "remove from white list" function will enable us to add some reasonable testing.

@eswarasai @pelsasser
