### ISSUE TITLE
[UI/UX] Avoid showing "Loading" text during initial load on Sim exchange for order book

### ISSUE THREAD

**Issue by nitinrgupta** [MARKETProtocol/dApp#425]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
To have consistent loading screen in sim exchange 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="1680" alt="screenshot 2018-10-10 at 4 44 54 pm" src="https://user-images.githubusercontent.com/4952395/46733292-80f8d600-ccad-11e8-8edb-69150394aa35.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Show the empty orderbook container div element while loading and before the loading indicator kicks in similar to other sections to have visual consistency 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
go to `/exchange`

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Have visual consistency for all the sections during the initial load

**Comment by eswarasai** [comment]
@nitinrgupta -- That's a bit of refactor in order to achieve the `Skeleton` mode if I'm not wrong. Hence went with the route of just adding a text at the moment to avoid the component crashing during loading especially when the order book API fails while fetching the data. It helps if you can attach a design or something on what's the expected behaviour so that we can understand the amount of work needed to get the intended UI/UX.

**Comment by nitinrgupta** [comment]
@eswarasai Like I mentioned in the expected behaviour, all the sections should look similar to have a visual consistency. 

Here's a mock to understand better what I'm expecting 
![group 59](https://user-images.githubusercontent.com/4952395/46734045-b56d9180-ccaf-11e8-955f-377acca10979.png)
