### ISSUE TITLE
Cannot create npm run build with current directory structure

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/Dapp#54]
build folder from truffle and build from npm are colliding!

**Comment by pelsasser** [comment]
Ha - 15 days ago - I cannot remember 2 days ago. ;) thanks @eswarasai

**Comment by pelsasser** [comment]
@eswarasai - can you please add as much information to this issue as possible and I will stake with ETH to get some help from gitcoin on it?

**Comment by eswarasai** [comment]
@pelsasser -- I've finally figured out which package is causing this issue. It's because of `is-ipfs` library which is being used in `src/components/TestQuery/OracleDataSources.js`.

@perfectmak -- Is there any alternative for the `is-ipfs` library as it's causing an issue while trying to run `npm run build` because the library source code is in `ES6` and `create-react-app` recommend using `ES5` in order to support older browser versions. Thanks.

**Comment by eswarasai** [comment]
@perfectmak -- For now, we're removing the IPFS feature from the dApp. In future, we can add this back once we have a work around for resolving the `create-react-app`

**Comment by eswarasai** [comment]
@pelsasser -- I've pushed a commit on `Dapp:master`. Please test if `npm run build` is working now or not and then close this issue. Thanks.

**Comment by pelsasser** [comment]
@eswarasai - this looks good! thanks! I will update documentation
